package ui

import "embed"

// DistFS embeds the built UI assets into the binary.
// Files are generated by: cd ui && npm run build
//
// The build outputs to pkg/ui/dist/ which is then embedded here.
// This allows the UI to be served from the Go binary without external files.
//
//go:embed all:dist
var DistFS embed.FS
