name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Vulntor
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below to help us fix the issue.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this issue?
      options:
        - 🔴 Critical (blocks usage, data loss, security issue)
        - 🟡 High (major feature broken, workaround exists)
        - 🟢 Medium (minor feature issue, easy workaround)
        - ⚪ Low (cosmetic, documentation)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Vulntor is affected?
      options:
        - Scanner (port scanning, discovery)
        - Engine (DAG, orchestrator, modules)
        - Plugin System (loader, cache, evaluator)
        - CLI (commands, flags, output)
        - Server (API, UI, background jobs)
        - Storage (workspace, scans, data persistence)
        - Configuration (config files, env vars)
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: Clear description of what's broken
      placeholder: |
        Example:
        When running `vulntor scan --targets 192.168.1.0/24 --vuln`, the scan completes but no vulnerabilities are reported even though the target has known issues.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. Run `vulntor plugin update`
        2. Execute `vulntor scan --targets 192.168.1.100 --ports 22 --vuln`
        3. Observe output
        4. Expected: Should detect SSH weak cipher
           Actual: No vulnerabilities reported
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: Should detect and report SSH weak cipher vulnerability
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: |
        No vulnerabilities reported. Output shows:
        ```
        Scan completed successfully
        Vulnerabilities found: 0
        ```
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Output
      description: Paste relevant logs, error messages, or output
      placeholder: |
        ```
        $ vulntor scan --targets 192.168.1.100 --ports 22 --vuln -vvv
        [DEBUG] Loading plugins from cache...
        [ERROR] Plugin evaluation failed: trigger[0]: data_key is required
        ```
      render: shell

  - type: input
    id: version
    attributes:
      label: Vulntor Version
      description: Output of `vulntor version`
      placeholder: "v0.1.0-dev (commit: abc1234)"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: OS and version
      placeholder: "macOS 14.6.0 (Darwin 24.6.0)"
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: Output of `go version` (if building from source)
      placeholder: "go1.24.0 darwin/arm64"

  - type: textarea
    id: root-cause
    attributes:
      label: Root Cause Analysis (Optional)
      description: If you've investigated, what's causing this?
      placeholder: |
        In `pkg/plugin/types.go:149-156`, the Validate() method requires `data_key` field but some plugins use `port` and `service` fields instead.

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution (Optional)
      description: Ideas for fixing this issue
      placeholder: |
        Option 1: Update Trigger struct to support port/service fields
        Option 2: Transform port/service triggers to data_key format during load
        Option 3: Update plugin YAML files to use data_key triggers

  - type: textarea
    id: workaround
    attributes:
      label: Workaround (Optional)
      description: Temporary solution that works
      placeholder: Skip vulnerability checks and use embedded plugins only

  - type: textarea
    id: related-files
    attributes:
      label: Related Files
      description: Code locations related to this issue
      placeholder: |
        - `pkg/plugin/types.go:149-156` (Validate method)
        - `pkg/plugin/cache.go:27-41` (CacheManager initialization)
        - `cmd/vulntor/commands/plugin/update.go:171-179` (cache check logic)

  - type: checkboxes
    id: impact
    attributes:
      label: Impact
      description: Who is affected by this bug?
      options:
        - label: Blocks development work
        - label: Affects end users
        - label: Breaks CI/CD
        - label: Security vulnerability
        - label: Data corruption risk

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: This issue started after upgrading to v0.1.0
