name: Multi-Platform Go Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]

    name: Test on linux / ${{ matrix.goarch }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run tests
        run: |
          mkdir -p coverage
          GOOS=linux GOARCH=${{ matrix.goarch }} make test-unit
          mv cover.out coverage/cover-linux-${{ matrix.goarch }}.out

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: cover-linux-${{ matrix.goarch }}
          path: coverage/cover-linux-${{ matrix.goarch }}.out

  merge-coverage:
    needs: test
    runs-on: ubuntu-latest
    name: Merge Coverage Reports

    steps:
      - uses: actions/checkout@v3

      - name: Download all coverage files
        uses: actions/download-artifact@v3
        with:
          path: merged-coverage

      - name: Install gocovmerge
        run: go install github.com/wadey/gocovmerge@latest

      - name: Merge coverage files
        run: |
          mkdir -p coverage
          gocovmerge $(find merged-coverage -name 'cover-*.out') > coverage/combined.out

      - name: Generate HTML report
        run: go tool cover -html=coverage/combined.out -o coverage/coverage.html

      - name: Upload combined coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
